### ISSUE TITLE
Issues with KeyError

### ISSUE THREAD

**Issue by LastAncientOne** [JerBouma/FundamentalAnalysis#11]
Traceback (most recent call last):

  File "<ipython-input-14-1520c9802762>", line 1, in <module>
    income_statement_annually = fa.income_statement(ticker, period="annual")

  File "C:\Users\Bob\Anaconda3\lib\site-packages\FundamentalAnalysis\financial_statements.py", line 28, in income_statement
    data_json = json.loads(data)['financials']   
 data_json = json.loads(data)['financials']

KeyError: 'financials'

**Comment by JerBouma** [comment]
I am aware of the issue, this is due to a new API. Will fix in the upcoming days.

**Comment by JerBouma** [comment]
With release 0.2.2, this issue is now fixed. Please update to the latest release.
